<?php

namespace TestEngine\Bundle\CoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use TestEngine\Bundle\CoreBundle\Document\Account;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends DocumentRepository
{
    public function addAccount($data)
    {
        if ($data) {
            $obj = $this->map($data);

            $this->dm->persist($obj);
            $this->dm->flush();

            return $obj;
        }

        return false;
    }

    protected function map($data)
    {
        $document = new Account();

        if (isset($data['user_id'])) {
            $document->setUserId($data['user_id']);
        }

        if (isset($data['package_id'])) {
            $document->setPackageId($data['package_id']);
        }

        if (isset($data['current_number_of_companies'])) {
            $document->setCurrentNumberOfCompanies($data['current_number_of_companies']);
        }

        if (isset($data['current_number_of_users'])) {
            $document->setCurrentNumberOfUsers($data['current_number_of_users']);
        }


        return $document;
    }
}