<?php

namespace TestEngine\Bundle\CoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use TestEngine\Bundle\CoreBundle\Document\Companies;

/**
 * CompaniesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompaniesRepository extends DocumentRepository
{
    public function addCompany($data)
    {
        if ($data) {
            $obj = $this->map($data);

            $this->dm->persist($obj);
            $this->dm->flush();

            return $obj;
        }

        return false;
    }

    protected function map($data)
    {
        $document = new Companies();

        if (isset($data['name'])) {
            $document->setName($data['name']);
        }

        if (isset($data['account_id'])) {
            $document->setAccountId($data['account_id']);
        }

        return $document;
    }
}