<?php

namespace TestEngine\Bundle\CoreBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use TestEngine\Bundle\CoreBundle\Document\Packages;

/**
 * PackagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackagesRepository extends DocumentRepository
{
    public function addPackage($data)
    {
        if ($data) {
            $package = $this->map($data);

            $this->dm->persist($package);
            $this->dm->flush();

            return $package;
        }

        return false;
    }

    protected function map($data)
    {
        $package = new Packages();

        if (isset($data['title'])) {
            $package->setTitle($data['title']);
        }

        if (isset($data['limit_company_count'])) {
            $package->setLimitCompanyCount($data['limit_company_count']);
        }

        if (isset($data['limit_user_count'])) {
            $package->setLimitUserCount($data['limit_user_count']);
        }

        if (isset($data['roles'])) {
            $package->setRoles($data['roles']);
        }


        return $package;
    }
}