<?php

namespace Threedots\Bundle\SsoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    public function getUserInfoByEmailAndPassword($login, $password)
    {
        $password = md5($password);

        $dql = "SELECT users FROM ThreedotsSsoBundle:Users as users
                            WHERE users.login = '$login'
                              AND users.password ='$password'";

        $result = $this->getEntityManager()
                       ->createQuery($dql)
                       ->setHydrationMode(2) // associative as array
                       ->getOneOrNullResult();

        return $result ? (object)$result : false;
    }
}